---
title: "pipeline"
output: html_document
date: "2023-11-08"
editor_options: 
  markdown: 
    wrap: 72
---

Installing packages and dependencies.

```{r}
# if (!require("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install(version = "3.17")
# 



pkgs = c( "edgeR", "gplots", "tximport", "biomaRt","BiocManSeq2","ComplexHeatmap",
          "ConsensusClusterPlus","TCGAbiolinks")
BiocManager::install(pkgs)




```

Loading Packages

```{r}
library(TCGAbiolinks)
library(dplyr)
library(DT)
library(DESeq2)
```

Getting Query

```{r}
query <- GDCquery(
  project = c("TCGA-STAD"),#Stomach
  data.category = "Transcriptome Profiling",
  data.type = "Gene Expression Quantification",
  access="open",
  experimental.strategy = "RNA-Seq",
  

)



datatable(
  getResults(query), 
  filter = 'top',
  options = list(scrollX = TRUE, keys = TRUE, pageLength = 5), 
  rownames = FALSE
)

```

Choosing Barcodes and downloading Data

```{r}
query <- GDCquery(
  project = c("TCGA-STAD"),#Stomach
  data.category = "Transcriptome Profiling",
  data.type = "Gene Expression Quantification",
  access="open",
  experimental.strategy = "RNA-Seq",
  barcode=c('TCGA-FP-7735-11A-01R-2055-13',
            'TCGA-FP-7735-01A-11R-2055-13',
            'TCGA-BR-6457-01A-21R-1802-13',
            'TCGA-BR-6457-11A-01R-1802-13',
            'TCGA-HU-8238-01A-11R-2343-13',
            'TCGA-HU-8238-11A-01R-2343-13')
)

getResults(query)
GDCdownload(query)
```

```{r}
tcga_br<-GDCprepare(query,summarizedExperiment = TRUE)
tcga_br_counts <- assay(tcga_br,'unstranded')  
tcga_br_tpm <- assay(tcga_br,'tpm_unstrand') 
br_Cor <-  TCGAanalyze_Preprocessing(tcga_br)



```

Preprocessing: 1- Normalization -for gene length -for GC content -for
total expression 2- data Filtering

```{r}
dataNorm <- TCGAanalyze_Normalization(
  tabDF = br_Cor, 
  geneInfo =  geneInfoHT)
  
# quantile filter of genes
# dataFilt <- TCGAanalyze_Filtering(
#   tabDF = dataNorm,
#   method = "quantile", 
#   qnt.cut =  0.25
# )
dataFilt <- t(dataNorm %>% 
  TCGAanalyze_Filtering(method = "varFilter") %>%
  TCGAanalyze_Filtering(method = "filter1") %>%  
  TCGAanalyze_Filtering(method = "filter2",foldChange = 1))
#dataFilt=dataFilt[c(sample(1:5000,2000)),]

```

```{r}
# selection of normal samples "NT"
samplesNT <- TCGAquery_SampleTypes(
  barcode = colnames(dataFilt),
  typesample = c("NT")
)

# selection of tumor samples "TP"
samplesTP <- TCGAquery_SampleTypes(
  barcode = colnames(dataFilt), 
  typesample = c("TP")
)

# Diff.expr.analysis (DEA)
dataDEGs <- TCGAanalyze_DEA(
  mat1 = dataFilt[,samplesNT],
  mat2 = dataFilt[,samplesTP],
  metadata=TRUE,
  pipeline = "edgeR",
  
  Cond1type = "Normal",
  Cond2type = "Tumor",
  fdr.cut = 0.05 ,
  logFC.cut = 1,
  method = "glmLRT"
)


# DEGs table with expression values in normal and tumor samples
dataDEGsFiltLevel <- TCGAanalyze_LevelTab(
  FC_FDR_table_mRNA = dataDEGs,
  typeCond1 = "Tumor",
  typeCond2 = "Normal",
  TableCond1 = dataFilt[,samplesTP],
  TableCond2 = dataFilt[,samplesNT]
)

```

Enrichment Analysis EA (TCGAVisualize) Gene Ontology (GO) and Pathway
enrichment barPlot

```{r}
library(EnsDb.Hsapiens.v86)

Genelist <- rownames(dataDEGsFiltLevel)
geneIDs <- ensembldb::select(EnsDb.Hsapiens.v86, keys= Genelist, keytype = "GENEID", columns = c("SYMBOL","GENEID") )

ansEA <- TCGAanalyze_EAcomplete(
  TFname = "DEA genes Normal Vs Tumor",
  RegulonList = geneIDs$SYMBOL
)



TCGAvisualize_EAbarplot(
  tf = rownames(ansEA$ResBP), 
  GOBPTab = ansEA$ResBP,
  GOCCTab = ansEA$ResCC,
  GOMFTab = ansEA$ResMF,
  PathTab = ansEA$ResPat,
  nRGTab = Genelist, 
  nBar = 10
)

```


PCA
```{r}

# Principal Component Analysis plot for ntop selected DEGs
pca <- TCGAvisualize_PCA(
    dataFilt = dataFilt,
    dataDEGsFiltLevel = dataDEGsFiltLevel,
    ntopgenes = 200, 
    group1 = samplesNT,
    group2 =  samplesTP
)


```









Clustering 
(Upon execution, R crashes. !?)
```{r}
data_Hc2 <- TCGAanalyze_Clustering(
  tabDF = dataFilt,method='consensus',methodHC = 'ward.D2')



colData(tcga_br)$groupsHC <- paste0("EC",data_Hc2[[4]]$consensusClass)

```